id: P5BC3454B
initial_creation_type: input
source_metadata:
  Title: Guṇakāraṇḍavyūha sūtram
  Editor: Chandra, Lokesh
  Publisher: International Academy of Indian Culture
  Place of Publication: India
  Year: '1999'
  1. śrītriratna bhajanānuśaṃsāvadānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2. avīci saṃśoṣaṇa śrīdharmarājābhibodhana prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3. sūcīmukhodara parvata pretoddhāraṇa prakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4. śrīmaheśvarādi deva samutpādana prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5. sarvākāra sarvasattva prabodhana bodhicaryāvatāraṇa prakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  6. durdānta dānava prabodhana bodhicaryāvatāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  7. adhomukha sattvoddhāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  8. rūpamayī bhūmi catuṣpāda puruṣoddhāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  9. bali saṃbodhana bodhimārgāvatāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  10. tamondhakāra bhūmi yakṣa rākṣasa paribodhana saddharmāvatāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  11. śuddhāvāsika sukuṇḍala devaputroddhāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  12. siṃhaladvīpa rākṣasī paribodhanoddhāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  13. vārāṇasī kṛmi kīṭoddhāraṇa prakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  14. māgadhika sattva prabodhanoddhāraṇa prakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  15. śrījetārāma viśvabhū darśana sukhāvatī pratyudgama prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  16. siṃhala sārthavāhoddhāraṇa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  17. sarvasattvoddhāraṇa saṃbodhimārga sthāpana maheśvaromādevī saṃbodhi vyākaraṇopadeśa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  18. sarva sabhāloka saddharma śravaṇotsāha saṃpramodita svasvālaya pratigamana prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  19. sikṣā saṃvara samuddeśa prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  20. phalaśrutiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:02:54.400992'
last_modified_at: '2022-03-08T16:02:54.401008'
